# Project: Final
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = principal.o
LINKOBJ  = principal.o
LIBS     = -L"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Andrea/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Final.exe
CXXFLAGS = $(CXXINCS) -g
CFLAGS   = $(INCS) -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

principal.o: principal.cpp
	$(CPP) -c principal.cpp -o principal.o $(CXXFLAGS)
